######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 8 22:23:49 2010
######################################################################

TEMPLATE = app
TARGET = cacheSim
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += Cache.h Memory.h MainWindow.h \
    Processor.h \
    Exceptions.h \
    AboutWindow.h
SOURCES += Cache.cpp main.cpp Memory.cpp MainWindow.cpp \
    Processor.cpp \
    AboutWindow.cpp
